name: Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 1: Install PHP and MySQL
      - name: Install PHP, MySQL, and Dependencies
        run: |
          sudo apt update
          sudo apt install -y php php-cli php-mysql unzip mariadb-server mariadb-client curl

      # Step 2: Start MariaDB Service
      - name: Start MariaDB Service
        run: |
          sudo systemctl start mariadb
          sudo systemctl enable mariadb
          sudo systemctl restart mariadb

      # Step 3: Setup MySQL Database
      - name: Setup Database
        run: |
          sudo mysql --user=root --execute="CREATE DATABASE IF NOT EXISTS quiz_pengupil;"
          sudo mysql --user=root quiz_pengupil < db/quiz_pengupil.sql
          sudo mysql --user=root --execute="GRANT ALL PRIVILEGES ON quiz_pengupil.* TO 'root'@'localhost' IDENTIFIED BY '';"
          sudo mysql --user=root --execute="FLUSH PRIVILEGES;"

      # Step 4: Verify Database Setup
      - name: Verify Database Setup
        run: |
          sudo mysql -u root -e "USE quiz_pengupil; SHOW TABLES;"

      # Step 5: Start PHP server
      - name: Start PHP Server
        run: |
          nohup php -S 127.0.0.1:8000 -t . > server.log 2>&1 &
          sleep 5
          echo "✅ Checking server log:"
          cat server.log

      # Step 6: Wait for the server to start
      - name: Wait for server to start
        run: |
          for i in {1..10}; do
            curl -s http://127.0.0.1:8000/ && echo "✅ Server is up!" && exit 0
            echo "⏳ Waiting for server..."
            sleep 2
          done
          echo "❌ Server failed to start!"
          exit 1

      # Step 7: Set Up Python
      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.4'

      # Step 8: Install Python Dependencies
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium

      # Step 9: Install Firefox & GeckoDriver
      - name: Install Firefox & GeckoDriver
        run: |
          sudo apt update
          sudo apt install -y firefox
          
          GECKODRIVER_VERSION=$(curl -sS https://api.github.com/repos/mozilla/geckodriver/releases/latest | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')
          wget -q "https://github.com/mozilla/geckodriver/releases/download/v$GECKODRIVER_VERSION/geckodriver-v$GECKODRIVER_VERSION-linux64.tar.gz"
          tar -xzf geckodriver-v$GECKODRIVER_VERSION-linux64.tar.gz
          sudo mv geckodriver /usr/local/bin/
          chmod +x /usr/local/bin/geckodriver

      # Step 10: Verify Firefox Installation
      - name: Verify Firefox Installation
        run: firefox --version

      # Step 11: Run Selenium Tests
      - name: Run Selenium Tests
        run: python -m unittest discover -s . -p "test_quiz_pengupil.py"

      # Step 12: Report Test Results
      - name: Report Test Results
        if: ${{ failure() }}
        run: echo "❌ Some tests failed. Please check the logs."
